import {
  IsString,
  IsOptional,
  IsArray,
  IsNumber,
  IsBoolean,
  IsEnum,
  ValidateNested,
  IsEmail,
  IsDateString,
  Min,
  Max,
} from 'class-validator';
import { Type } from 'class-transformer';
import { ApiProperty, ApiPropertyOptional } from '@nestjs/swagger';
import { PaymentMethod } from '@prisma/client';

export class CheckoutTicketDto {
  @IsString()
  @ApiProperty({ description: 'Ticket ID', example: 'uuid' })
  ticketId: string;

  @IsNumber()
  @Min(1)
  @Type(() => Number)
  @ApiProperty({ description: 'Quantity of tickets', example: 2 })
  quantity: number;

  @IsOptional()
  @IsString()
  @ApiPropertyOptional({ description: 'Batch ID (optional, will use active batch if not provided)', example: 'uuid' })
  batchId?: string;
}

export class CheckoutProductDto {
  @IsString()
  @ApiProperty({ description: 'Product ID', example: 'uuid' })
  productId: string;

  @IsOptional()
  @IsString()
  @ApiPropertyOptional({ description: 'Product variation ID', example: 'uuid' })
  variationId?: string;

  @IsNumber()
  @Min(1)
  @Type(() => Number)
  @ApiProperty({ description: 'Quantity', example: 1 })
  quantity: number;
}

export class CheckoutQuestionAnswerDto {
  @IsString()
  @ApiProperty({ description: 'Question ID', example: 'uuid' })
  questionId: string;

  @ApiProperty({ description: 'Answer (string, boolean, or number)', example: 'Resposta' })
  answer: string | boolean | number;
}

export class CheckoutParticipantDto {
  @IsString()
  @ApiProperty({ description: 'Participant name', example: 'João Silva' })
  name: string;

  @IsString()
  @ApiProperty({ description: 'CPF (numbers only)', example: '12345678900' })
  cpf: string;

  @IsEmail()
  @ApiProperty({ description: 'Email', example: 'joao@example.com' })
  email: string;

  @IsDateString()
  @ApiProperty({ description: 'Birth date (ISO 8601)', example: '1990-01-01' })
  birthDate: string;

  @IsString()
  @ApiProperty({ description: 'Phone', example: '11999999999' })
  phone: string;

  @IsOptional()
  @IsEnum(['MALE', 'FEMALE', 'OTHER', 'PREFER_NOT_TO_SAY'])
  @ApiPropertyOptional({ description: 'Gender', enum: ['MALE', 'FEMALE', 'OTHER', 'PREFER_NOT_TO_SAY'] })
  gender?: string;

  @IsOptional()
  @IsString()
  @ApiPropertyOptional({ description: 'Emergency contact name', example: 'Maria Silva' })
  emergencyContactName?: string;

  @IsOptional()
  @IsString()
  @ApiPropertyOptional({ description: 'Emergency phone', example: '11988888888' })
  emergencyPhone?: string;

  @IsOptional()
  @IsBoolean()
  @ApiPropertyOptional({ description: 'Has emergency contact', default: false })
  hasEmergencyContact?: boolean;

  @IsOptional()
  @IsArray()
  @ValidateNested({ each: true })
  @Type(() => CheckoutQuestionAnswerDto)
  @ApiPropertyOptional({ description: 'Question answers', type: [CheckoutQuestionAnswerDto] })
  questionAnswers?: CheckoutQuestionAnswerDto[];

  @IsOptional()
  @IsArray()
  @ValidateNested({ each: true })
  @Type(() => CheckoutProductDto)
  @ApiPropertyOptional({ description: 'Products for this participant', type: [CheckoutProductDto] })
  products?: CheckoutProductDto[];
}

export class CheckoutCardDto {
  @IsString()
  @ApiProperty({ description: 'Cardholder name', example: 'JOÃO SILVA' })
  name: string;

  @IsString()
  @ApiProperty({ description: 'Card number (last 4 digits after validation)', example: '1234' })
  number: string;

  @IsString()
  @ApiProperty({ description: 'Expiry date (MM/YY)', example: '12/25' })
  expiry: string;

  @IsString()
  @ApiProperty({ description: 'CVV', example: '123' })
  cvv: string;

  @IsNumber()
  @Min(1)
  @Max(12)
  @Type(() => Number)
  @ApiProperty({ description: 'Number of installments (1-12)', example: 1 })
  installments: number;
}

export class CheckoutPaymentDto {
  @IsOptional()
  @ValidateNested()
  @Type(() => CheckoutCardDto)
  @ApiPropertyOptional({ description: 'Credit card data', type: CheckoutCardDto })
  card?: CheckoutCardDto;

  // PIX and Boleto data will be generated by payment gateway
}

export class ProcessCheckoutDto {
  @IsString()
  @ApiProperty({ description: 'Event ID', example: 'uuid' })
  eventId: string;

  @IsEnum(PaymentMethod)
  @ApiProperty({ description: 'Payment method', enum: PaymentMethod, example: PaymentMethod.PIX })
  paymentMethod: PaymentMethod;

  @ValidateNested()
  @Type(() => CheckoutPaymentDto)
  @ApiProperty({ description: 'Payment data', type: CheckoutPaymentDto })
  payment: CheckoutPaymentDto;

  @IsArray()
  @ValidateNested({ each: true })
  @Type(() => CheckoutTicketDto)
  @ApiProperty({ description: 'Selected tickets', type: [CheckoutTicketDto] })
  tickets: CheckoutTicketDto[];

  @IsArray()
  @ValidateNested({ each: true })
  @Type(() => CheckoutParticipantDto)
  @ApiProperty({ description: 'Participants (one for each ticket)', type: [CheckoutParticipantDto] })
  participants: CheckoutParticipantDto[];

  @IsOptional()
  @IsString()
  @ApiPropertyOptional({ description: 'Coupon code', example: 'PROMO2024' })
  couponCode?: string;

  @IsOptional()
  @IsString()
  @ApiPropertyOptional({ description: 'Voucher code', example: 'ABC12345' })
  voucherCode?: string;
}
