module.exports = {
  moduleFileExtensions: ['js', 'json', 'ts'],
  rootDir: 'src',
  testRegex: '.*\\.spec\\.ts$',
  transform: {
    '^.+\\.(t|j)s$': 'ts-jest',
  },
  collectCoverageFrom: [
    'app/events/**/*.ts',
    'app/organizers/**/*.ts',
    'app/registrations/**/*.ts',
    'app/kits/**/*.ts',
    'app/modalities/**/*.ts',
    'app/questions/**/*.ts',
    'app/user/**/*.ts',
    'app/auth/**/*.ts',
    'app/payments/**/*.ts',
    'app/upload/**/*.ts',
    'common/services/email.service.ts',
    'common/services/whatsapp.service.ts',
    '!**/*.module.ts',
    '!**/*.dto.ts',
    '!**/*.entity.ts',
    '!**/*.config.ts',
    '!**/main.ts',
    '!**/index.ts',
    '!**/*.spec.ts',
  ],
  coverageDirectory: '../coverage',
  testEnvironment: 'node',
  moduleNameMapper: {
    '^src/(.*)$': '<rootDir>/$1',
  },
  moduleDirectories: ['node_modules', 'src'],
  modulePaths: ['<rootDir>'],
  testTimeout: 30000,
  verbose: true,
  collectCoverage: false,
  coverageReporters: ['text', 'lcov', 'html', 'json-summary'],
  coverageThreshold: {
    global: {
      branches: 70,
      functions: 75,
      lines: 80,
      statements: 80,
    },
  },
  clearMocks: true,
  restoreMocks: true,
  detectOpenHandles: true,
  forceExit: true,
};
